### PR TITLE
Fixes #114

### LINKED ISSUE #114: Instructions missing for installation with Textmate
SSIA

### PR DESCRIPTION
**Pull request by dhensche**
Created a tmbundle folder that TextMate 2 uses for installing bundles.
Didn't touch any of the other files. I created this bundle in a way I would consider
hackish, but it seems to work. Basically I created a new bundle and then 'applied'
the tmLanguage and tmPreferences files to it.

### CODE REVIEW

**Comment by zertosh** [comment]
How do you keep the tmbundle directory updated when you change the YAML-* files?

**Comment by simonzack** [comment]
Agree with @zertosh, we need something cleaner, perhaps a script to generate the bundles or some other way to reduce file duplication.

**Comment by dhensche** [comment]
I agree with you guys, I only created the pull request so I could get the tmBundle to @jeduan. I think there should really only be one copy of the bundle files, I just don't know much about creating bundles or what the YAML files were for. There probably was a better way for me to get him the bundle...

**Comment by zertosh** [comment]
@dhensche I'm sorry but I think we have a misunderstanding. The problem is not generating the tm* files from the YAML files, we use AAAPackageDev (see [contributing](https://github.com/Benvie/JavaScriptNext.tmLanguage#contributing)) right from Sublime for that. Plus, you can't just delete them - Sublime users need those. The issue is how do you automate the tmBundle creation once those are created w/o making it super manual or complicated.

Looking at your changes, it seems like you def need an `info.plist` - but the files need to be in that directory structure? Can't a TextMate user just clone the repo into a directory called `JavaScriptNext.tmbundle`?

Last thing, I'm pretty sure that changing the scope to `scopeName: source.js.es6` breaks things (at least for Sublime users).

**Comment by Paxa** [comment]
Worked well, thanks

**Comment by sgarbesi** [comment]
This should be bundled.

**Pull request closed without merging**
