### PR TITLE
Update list of Node core modules

### PR DESCRIPTION
**Pull request by sindresorhus**
From: https://github.com/sindresorhus/builtin-modules

### CODE REVIEW

**Comment by zertosh** [comment]
heh [`console`](https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/efd7c4c28156e417a3b1184b146eff28ee54c887/JavaScriptNext.YAML-tmLanguage#L1095) and [`module`](https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/efd7c4c28156e417a3b1184b146eff28ee54c887/JavaScriptNext.YAML-tmLanguage#L1117) are already matched

**Comment by sindresorhus** [comment]
Those are globals though. These you can require. Not sure if that makes a difference though? But would be weird to use an incomplete list. Does it matter if they stay? Otherwise I'm happy to remove them.

**Comment by zertosh** [comment]
> Those are globals though. These you can require. Not sure if that makes a difference though

Nope. Sublime's regex doesn't allow that level of sophistication. It's not like an AST, it's more like [`js-tokens`](https://github.com/lydell/js-tokens).

> But would be weird to use an incomplete list. Does it matter if they stay?

Technically, console won't but module will because of the order in which they appear. But it's even weirder to have a word in a match that you know won't actually match. That's super confusing when you're reading these files.

> Otherwise I'm happy to remove them.

Please do. The rest look awesome though! Thank you!

**Comment by sindresorhus** [comment]
Fixed.

**Comment by simonzack** [comment]
Thanks~

**Pull request merged**
