### PR TITLE
Add match for concise method definitions

### PR DESCRIPTION
**Pull request by zertosh**
Properly match [concise methods] [1]. Fixes:
1. "Go to symbol"  for concise methods (since `source.js meta.method.js` is already in `Symbol List Function.tmPreferences`),
2. And, those themes that specifically color methods (like mine :smile:)

[1]: http://ariya.ofilabs.com/2013/03/es6-and-method-definitions.html

EDIT: Added screenshot
symbols

### CODE REVIEW

**Comment by zertosh** [comment]
Closing for now. Sorry something doesn't look right. (and I uploaded the wrong screenshot too)

**Comment by simonzack** [comment]
No worries. Also, try to put it under `literal-class` if you can.

**Comment by zertosh** [comment]
I can't figure this one out. Everything I try ends in a bust. I'm trying to match short method definitions (in plain objects, not classes) so they can be properly listed as symbols. I don't think it's possible to distinguish between a function call and short method definition using regexs. @simonzack Any ideas?

```js
var obj = {
  dogs: function() {
    // matches as "meta.function"
  },
  cats() {
    // matches as "meta.function-call"
  }
};
```

**Comment by simonzack** [comment]
@zertosh What a coincidence, I did an implementation just yesterday.

The way I did it was to match the ending `{`, and hope that the definition is all on one line, otherwise I don't know of any way to distinguish between them either :(

I also thought about determining whether the parent scope is an object or not, but that can't be known without knowing whether the first entry is a key: value pair or a short method definition, because it could be a block scope too.

**Comment by zertosh** [comment]
@simonzack: I just had a chance to look at your changes, very clever! Matching the opening curly is a fair compromise :stuck_out_tongue: 

I did notice on thing, if you have return type annotations, it won't match anymore.

```js
  makePath(/*string*/ name, /*?object*/ params) /*?object*/ {
    return router.makePath(name, params);
  },
```

**Comment by zertosh** [comment]
@simonzack: https://github.com/Benvie/JavaScriptNext.tmLanguage/pull/76 should fix the comments between params and the open curly.

**Pull request closed without merging**
