### PR TITLE
Added highlighting for leading '$' for use especially in angular.js

### PR DESCRIPTION
**Pull request by Rleahy22**

### CODE REVIEW

**Comment by simonzack** [comment]
I don't think this is quite right, you modified a part of the regex matcher. Put this under `support`.

**Comment by Rleahy22** [comment]
Are you saying you want Angular.js specific support?

**Comment by simonzack** [comment]
The `yaml` file is split up into sections, `support` is such a section, you can find it near the bottom of the file. I don't really mind whether it's angular specific or not, but I think it's commonly used enough that it could be helpful. It's just that your PR doesn't quite fix the problem, it changes the regex highlighter instead of adding a dollar variable highlighter.

**Comment by simonzack** [comment]
I've added this now.

**Comment by Rleahy22** [comment]
Great thank you

**Comment by simonzack** [comment]
You're welcome :)

**Pull request closed without merging**
