### PR TITLE
Broken square braces fix

### PR DESCRIPTION
**Pull request by zertosh**
Seems like https://github.com/Benvie/JavaScriptNext.tmLanguage/commit/6c3ad0e17e25f45e188c1f954d99d3da68fca85e caused this.

**before**
before

**after**
after

### CODE REVIEW

**Comment by zertosh** [comment]
cc: @simonzack

**Comment by simonzack** [comment]
@zertosh Fixed now. Sorry about this, I had to isolate expressions to separate the switch cases from object keys, which required a refactoring.

**Comment by zertosh** [comment]
@simonzack It's cool, thanks for fixing the `switch` thing. Sorry for the weird question: but do you work at Mozilla? Or is that just Benvie?

**Comment by simonzack** [comment]
@zertosh Just Benvie. I'm still doing masters of computer science and don't have a job yet, you know any job openings?

**Comment by zertosh** [comment]
@simonzack I sent you an email just now

**Pull request closed without merging**
